//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeSalesShop.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeSalesShop.API.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a user&apos;s first name can be {0} characters..
        /// </summary>
        internal static string FirstNameMaxCharsValidation {
            get {
                return ResourceManager.GetString("FirstNameMaxCharsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address. Please enter a valid email address..
        /// </summary>
        internal static string InvalidEmailValidation {
            get {
                return ResourceManager.GetString("InvalidEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a user&apos;s last name can be {0} characters..
        /// </summary>
        internal static string LastNameMaxCharsValidation {
            get {
                return ResourceManager.GetString("LastNameMaxCharsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum name length can be {0} characters..
        /// </summary>
        internal static string NameMaxCharsValidation {
            get {
                return ResourceManager.GetString("NameMaxCharsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with this code already exists..
        /// </summary>
        internal static string ProductCodeExists {
            get {
                return ResourceManager.GetString("ProductCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a product code can be {0} characters..
        /// </summary>
        internal static string ProductCodeMaxCharsValidation {
            get {
                return ResourceManager.GetString("ProductCodeMaxCharsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a product description can be {0} characters..
        /// </summary>
        internal static string ProductDescriptionMaxCharsValidation {
            get {
                return ResourceManager.GetString("ProductDescriptionMaxCharsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with that name already exists..
        /// </summary>
        internal static string ProductNameExists {
            get {
                return ResourceManager.GetString("ProductNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found..
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price of the product can be from 0 to 99999.99..
        /// </summary>
        internal static string ProductPriceValidation {
            get {
                return ResourceManager.GetString("ProductPriceValidation", resourceCulture);
            }
        }
    }
}
